[package]
name = "r-json_event_parser"
version = "0.1.0"
authors = ["Julien Férard <julien_ferard@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "json2xml"
[dependencies]
clap = "2.33.3"